---
- name: Update cache
  apt: update_cache=yes
  become: yes
  become_method: sudo

- name: Setup base tools
  apt: name={{ item }} state=present
  become: yes
  become_method: sudo
  with_items:
    - vim
    - git
    - mercurial
    - python-setuptools
    - python-dev
    - postgresql
    - libpq-dev
    - unzip
    - libaio1
    - python-psycopg2
    - libtiff5-dev
    - libjpeg8-dev
    - zlib1g-dev
    - libfreetype6-dev

- name: install pip
  easy_install: name=pip
  become: yes
  become_method: sudo

- name: install virtualenv
  pip: name=virtualenv
  become: yes
  become_method: sudo


- name: install les paquets pip
  pip: name={{ item }} virtualenv={{ansible_env.HOME}}/{{ virtualenv.dir }}/{{ virtualenv.name }}
  environment:
    HOME: /home/{{ user }}
    ORACLE_HOME: "{{ oracle_client_base }}/instantclient_{{ oracle_version.majeur }}_{{ oracle_version.mineur }}"
  with_items: pip_modules

- name: installing wkhtmltopdf
  unarchive: src=wkhtmltox.tar.xz dest=/opt
  become: yes
  become_method: sudo

- name: link wkhtmltopdf
  file: src=/opt/wkhtmltox/bin/wkhtmltopdf dest=/usr/local/bin/wkhtmltopdf state=link
  become: yes
  become_method: sudo