---

- name: clone duck_eggs
  git: "repo=https://github.com/iedparis8/{{ item}}.git
       dest={{ansible_env.HOME}}/{{ project.dir }}/{{ item}}
       update=no"
  with_items: duck_module
  tags:
    - git
    - install

- name: update duck_eggs
  git: "repo=https://github.com/iedparis8/{{ item}}.git
       dest={{ansible_env.HOME}}/{{ project.dir }}/{{ item}}"
  with_items: duck_module
  tags:
    - git_update
    - git
