---
# handlers file for nginx
- name: stop supervisord
  service: name=supervisord state=stopped
  become: yes
  become_method: sudo

- name: start supervisord
  service: name=supervisord state=started
  become: yes
  become_method: sudo