---
# tasks file for supervisorctl
- name: install supervisord
  pip: name=supervisor
  become: yes
  become_method: sudo

- name: create supervisord dir
  file: path="{{ item }}" state=directory
  become: yes
  become_method: sudo
  ignore_errors: True
  with_items:
    - "{{supervisord_conf_dir}}"
    - /var/log/supervisor


- name: conf supervisord
  template: src=supervisord.conf.j2 dest=/etc/supervisor/supervisord.conf
  become: yes
  become_method: sudo

- name: obtaining installation directory
  shell: ls -d /opt/instantclient_1[012]_*
  register: ls_oracle_home
  changed_when: false
  tags: instal

- name: init supervisord
  template: src=init.conf.j2 dest=/etc/init.d/supervisord
  become: yes
  become_method: sudo

- name: permission on supervisord init
  file: path=/etc/init.d/supervisord mode="u+x,o+x,g+x"
  become: yes
  become_method: sudo

- name: create supervisord dir
  file: path="{{ansible_env.HOME}}/logs/{{ item }}" state=directory
  with_items: sites.keys()

- name: Create the configurations for sites
  template: src=site.conf.j2 dest={{supervisord_conf_dir}}/{{ item }}.conf
  with_items: sites.keys()
  notify:
    - stop supervisord
    - start supervisord
  tags: [configuration,supervisord]
  become: yes
  become_method: sudo
  ignore_errors: True