---
# tasks file for supervisorctl
- name: install supervisord
  pip: name=supervisor
  become: yes
  become_method: sudo

- name: conf supervisord
  command: echo_supervisord_conf > /etc/supervisord.conf
  become: yes
  become_method: sudo

- name: init supervisord
  template: src=init.conf.j2 dest=/etc/init.d/supervisord
  become: yes
  become_method: sudo


- name: create supervisord conf
  file: path=/etc/supervisord/conf.d state=directory
  become: yes
  become_method: sudo
  ignore_errors: True

- name: Create the configurations for sites
  template: src=site.conf.j2 dest={{supervisord_conf_dir}}/{{ item }}.conf
  with_items: sites.keys()
  notify:
    - restart supervisord
  tags: [configuration,supervisord]
  become: yes
  become_method: sudo
  ignore_errors: True