---
# tasks file for postgresl
- name: Copy valid pg_hba.conf
  template: src=pg_hba.conf.j2 dest=/etc/postgresql/9.3/main/pg_hba.conf
  become: yes
  become_method: sudo
  notify:
    - Restart PostgreSQL


- name: Postgres installation database
  become: yes
  become_user: postgres
  become_method: sudo
  postgresql_db: name={{ postgres_database }} encoding='UTF-8'


- name: Posgres user
  become: yes
  become_user: postgres
  become_method: sudo
  postgresql_user: name={{ postgres_user }} db={{ postgres_database }} password={{ postgres_password }} role_attr_flags=SUPERUSER