---
# tasks file for nginx
- name: install nginx
  apt: name=nginx
  become: yes
  become_method: sudo

- name: Create the configurations for sites
  template: src=site.conf.j2 dest={{nginx_conf_dir}}/sites-available/{{ item }}.conf
  with_items: sites.keys()
  notify:
   - restart nginx
  tags: [configuration,nginx]
  become: yes
  become_method: sudo


- name: Create the configurations for sites
  file: src={{nginx_conf_dir}}/sites-available/{{ item }}.conf dest={{nginx_conf_dir}}/sites-enabled/{{ item }} state=link
  with_items: sites.keys()
  notify:
   - restart nginx
  tags: [configuration,nginx]
  become: yes
  become_method: sudo

- copy: src=default.conf dest={{nginx_conf_dir}}/sites-available/default force=yes
  tags: [configuration,nginx]
  become: yes
  become_method: sudo

- name: remove default site
  file:  dest={{nginx_conf_dir}}/sites-enabled/default src={{nginx_conf_dir}}/sites-available/default  state=link
  notify:
   - restart nginx
  tags: [configuration,nginx]
  become: yes
  become_method: sudo
