---
# tasks file for nginx
- name: install nginx
  apt: name=nginx
  become: yes
  become_method: sudo

- name: Create the configurations for sites
  template: src=site.conf.j2 dest={{nginx_conf_dir}}/sites-available/{{ item }}.conf
  with_items: nginx_sites.keys()
  notify:
   - restart nginx
  tags: [configuration,nginx]
  become: yes
  become_method: sudo
  ignore_errors: True